### PR TITLE
refactor(polyclinic): migrate to clean architecture

### PR DESCRIPTION
**Pull request by dhichii**
## Tests
- [x] Create Polyclinic
- [x] Show All Polyclinics
- [x] Show Polyclinic by ID
- [x] Update Polyclinic by ID
- [x] Delete Polyclinic by ID

### CODE REVIEW

**Comment by thisham** [comment]
Prefer remove the past MVC.

**Comment by dhichii** [comment]
> Prefer remove the past MVC.

done

**Comment by thisham** [comment]
Please rename `src/app/polyclinic/services/usercases.go` to `src/app/polyclinic/services/usecases.go`.

**Comment by dhichii** [comment]
> 



> Please rename `src/app/polyclinic/services/usercases.go` to `src/app/polyclinic/services/usecases.go`.

Done. Sorry it's a typo

**Review by thisham — APPROVED** [review]
LGTM!

**Pull request merged**
